import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "var(--page-bg)",
    padding: "clamp(14px, 3.2vw, 26px) clamp(12px, 3vw, 24px) 132px",
    fontFamily: "\"Rubik\", \"Noto Sans Hebrew\", \"Segoe UI\", Arial, sans-serif",
    color: "var(--text-primary)",
    transition: "background 220ms ease, color 220ms ease",
  },
  pageThemeLight: {
    "--page-bg":
      "radial-gradient(circle at 12% -8%, rgba(34, 197, 94, 0.16), transparent 35%), radial-gradient(circle at 88% 8%, rgba(14, 165, 233, 0.2), transparent 38%), linear-gradient(180deg, #f4f8ff 0%, #e9f1ff 100%)",
    "--text-primary": "#0f172a",
    "--text-muted": "#334155",
    "--card-bg": "rgba(255,255,255,0.95)",
    "--card-border": "rgba(148, 163, 184, 0.2)",
    "--card-shadow": "0 10px 30px rgba(15, 23, 42, 0.08)",
    "--table-bg": "#ffffff",
    "--table-head-bg": "#f4f8fe",
    "--table-head-border": "#dbe4f0",
    "--table-row-border": "#e6edf5",
    "--soft-bg": "#f7fbff",
    "--soft-border": "#dbe6f3",
    "--bottom-bg": "rgba(245, 250, 255, 0.97)",
    "--bottom-border": "rgba(160, 184, 207, 0.38)",
    "--overlay-bg": "rgba(15, 23, 42, 0.34)",
    "--modal-bg": "rgba(255,255,255,0.98)",
    "--hero-bg":
      "linear-gradient(148deg, #072a42 0%, #0f4d78 42%, #1477c9 100%)",
    "--hero-text": "rgba(240, 249, 255, 0.88)",
    "--hero-metric-bg": "rgba(226, 242, 255, 0.14)",
    "--hero-metric-border": "rgba(226, 242, 255, 0.22)",
    "--hero-metric-label": "rgba(255,255,255,0.72)",
    "--stat-card-bg":
      "linear-gradient(180deg, rgba(255,255,255,0.98), rgba(243,248,255,0.96))",
    "--stat-card-border": "rgba(148, 163, 184, 0.2)",
    "--vehicle-box-bg": "linear-gradient(135deg, #dbeafe 0%, #eef2ff 100%)",
    "--vehicle-box-border": "rgba(96, 165, 250, 0.25)",
  } as CSSProperties,
  pageThemeDark: {
    "--page-bg":
      "radial-gradient(circle at 20% -10%, rgba(37, 99, 235, 0.2), transparent 40%), radial-gradient(circle at 80% 0%, rgba(14, 165, 233, 0.18), transparent 42%), linear-gradient(180deg, #070c18 0%, #0b1220 100%)",
    "--text-primary": "#e2e8f0",
    "--text-muted": "#94a3b8",
    "--card-bg": "rgba(15, 23, 42, 0.78)",
    "--card-border": "rgba(71, 85, 105, 0.55)",
    "--card-shadow": "0 14px 34px rgba(2, 6, 23, 0.45)",
    "--table-bg": "rgba(15, 23, 42, 0.82)",
    "--table-head-bg": "rgba(30, 41, 59, 0.95)",
    "--table-head-border": "rgba(71, 85, 105, 0.8)",
    "--table-row-border": "rgba(51, 65, 85, 0.75)",
    "--soft-bg": "rgba(30, 41, 59, 0.88)",
    "--soft-border": "rgba(71, 85, 105, 0.75)",
    "--bottom-bg": "rgba(15, 23, 42, 0.95)",
    "--bottom-border": "rgba(71, 85, 105, 0.9)",
    "--overlay-bg": "rgba(2, 6, 23, 0.62)",
    "--modal-bg": "rgba(10, 16, 30, 0.97)",
    "--hero-bg":
      "linear-gradient(145deg, rgba(2,6,23,0.96) 0%, rgba(15,23,42,0.96) 52%, rgba(30,64,175,0.82) 100%)",
    "--hero-text": "rgba(226, 232, 240, 0.92)",
    "--hero-metric-bg": "rgba(15, 23, 42, 0.72)",
    "--hero-metric-border": "rgba(71, 85, 105, 0.7)",
    "--hero-metric-label": "rgba(203, 213, 225, 0.86)",
    "--stat-card-bg":
      "linear-gradient(165deg, rgba(15,23,42,0.92), rgba(30,41,59,0.9))",
    "--stat-card-border": "rgba(71, 85, 105, 0.78)",
    "--vehicle-box-bg":
      "linear-gradient(145deg, rgba(30,41,59,0.92) 0%, rgba(15,23,42,0.92) 100%)",
    "--vehicle-box-border": "rgba(71, 85, 105, 0.85)",
  } as CSSProperties,
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
  },
  authCard: {
    maxWidth: "480px",
    margin: "60px auto",
    background: "var(--card-bg)",
    borderRadius: "24px",
    padding: "28px",
    boxShadow: "var(--card-shadow)",
    border: "1px solid var(--card-border)",
    backdropFilter: "blur(10px)",
    color: "var(--text-primary)",
  },
  centered: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "\"Segoe UI\", Arial, sans-serif",
    color: "var(--text-primary)",
    background: "var(--page-bg)",
  },
  topBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
    marginBottom: "8px",
    flexWrap: "wrap",
    position: "relative",
  },
  brandRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  brandLogo: {
    width: "52px",
    height: "52px",
    borderRadius: "14px",
    objectFit: "cover",
    boxShadow: "0 8px 20px rgba(15, 23, 42, 0.2)",
    border: "1px solid rgba(148, 163, 184, 0.35)",
    flexShrink: 0,
  },
  title: {
    fontSize: "clamp(21px, 4.6vw, 30px)",
    lineHeight: 1.05,
    marginBottom: "2px",
    marginTop: 0,
    letterSpacing: "-0.01em",
  },
  subtitle: {
    color: "var(--text-muted)",
    marginBottom: 0,
    fontSize: "12px",
    lineHeight: 1.3,
  },
  demoBanner: {
    background: "rgba(251, 191, 36, 0.16)",
    border: "1px solid rgba(217, 119, 6, 0.35)",
    color: "#92400e",
    borderRadius: "14px",
    padding: "10px 12px",
    marginBottom: "12px",
    fontSize: "14px",
    fontWeight: 600,
  },
  heroCard: {
    background: "var(--hero-bg)",
    color: "#ffffff",
    borderRadius: "26px",
    padding: "clamp(12px, 3.2vw, 20px)",
    marginBottom: "10px",
    boxShadow: "0 24px 50px rgba(8, 47, 73, 0.26)",
    border: "1px solid rgba(186, 230, 253, 0.26)",
  },
  heroEyebrow: {
    fontSize: "11px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    opacity: 0.76,
    marginBottom: "6px",
  },
  heroTitle: {
    fontSize: "clamp(20px, 5vw, 30px)",
    margin: 0,
    marginBottom: "4px",
    letterSpacing: "-0.02em",
  },
  heroText: {
    margin: 0,
    color: "var(--hero-text)",
    lineHeight: 1.35,
    maxWidth: "760px",
    fontSize: "12px",
  },
  heroMetrics: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))",
    gap: "8px",
    marginTop: "8px",
  },
  heroMetric: {
    background: "var(--hero-metric-bg)",
    border: "1px solid var(--hero-metric-border)",
    borderRadius: "12px",
    padding: "9px",
    backdropFilter: "blur(8px)",
  },
  heroMetricLabel: {
    fontSize: "11px",
    color: "var(--hero-metric-label)",
    marginBottom: "2px",
  },
  heroMetricValue: {
    fontSize: "clamp(16px, 3.8vw, 20px)",
    fontWeight: 700,
  },
  accountMenu: {
    position: "relative",
  },
  accountMenuTrigger: {
    listStyle: "none",
    width: "40px",
    height: "40px",
    borderRadius: "12px",
    border: "1px solid var(--soft-border)",
    background: "var(--soft-bg)",
    color: "var(--text-primary)",
    display: "grid",
    placeItems: "center",
    cursor: "pointer",
    fontSize: "18px",
    fontWeight: 700,
  },
  accountMenuPanel: {
    position: "absolute",
    top: "46px",
    right: 0,
    minWidth: "220px",
    background: "var(--table-bg)",
    border: "1px solid var(--soft-border)",
    borderRadius: "12px",
    padding: "10px",
    display: "grid",
    gap: "8px",
    boxShadow: "0 14px 24px rgba(15,23,42,0.22)",
    zIndex: 40,
  },
  accountMenuEmail: {
    fontSize: "12px",
    color: "var(--text-muted)",
    wordBreak: "break-all",
  },
  infoBox: {
    background: "rgba(255,255,255,0.8)",
    padding: "12px 16px",
    borderRadius: "16px",
    marginBottom: "20px",
    display: "inline-block",
    border: "1px solid rgba(148, 163, 184, 0.18)",
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.06)",
  },
  vehicleBox: {
    marginTop: "14px",
    background: "var(--vehicle-box-bg)",
    padding: "12px 16px",
    borderRadius: "16px",
    border: "1px solid var(--vehicle-box-border)",
    color: "var(--text-primary)",
  },
  card: {
    background: "var(--card-bg)",
    borderRadius: "22px",
    padding: "clamp(14px, 3.4vw, 24px)",
    marginBottom: "14px",
    boxShadow: "var(--card-shadow)",
    border: "1px solid var(--card-border)",
    backdropFilter: "blur(8px)",
  },
  sectionTitle: {
    marginTop: 0,
    marginBottom: "16px",
    fontSize: "22px",
  },
  authTabs: {
    display: "flex",
    gap: "10px",
    marginBottom: "16px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))",
    gap: "10px",
    marginBottom: "12px",
  },
  compactGridThree: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "8px",
    marginBottom: "10px",
  },
  compactControl: {
    minWidth: 0,
    position: "relative",
  },
  compactLabel: {
    display: "block",
    marginBottom: "4px",
    fontWeight: 700,
    fontSize: "13px",
    lineHeight: 1.2,
  },
  compactInput: {
    width: "100%",
    padding: "9px 10px",
    borderRadius: "10px",
    border: "1px solid var(--table-head-border)",
    fontSize: "14px",
    boxSizing: "border-box",
    background: "var(--table-bg)",
    color: "var(--text-primary)",
  },
  suggestList: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    zIndex: 30,
    marginTop: "4px",
    maxHeight: "220px",
    overflowY: "auto",
    borderRadius: "12px",
    border: "1px solid var(--table-head-border)",
    background: "var(--table-bg)",
    boxShadow: "0 10px 24px rgba(15,23,42,0.22)",
  },
  suggestOption: {
    width: "100%",
    padding: "10px 12px",
    border: "none",
    borderBottom: "1px solid var(--table-row-border)",
    background: "transparent",
    color: "var(--text-primary)",
    textAlign: "start",
    cursor: "pointer",
    fontSize: "14px",
  },
  mobileQuickForm: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "12px",
    marginBottom: "12px",
  },
  mobileQuickField: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  mobileBigInput: {
    width: "100%",
    padding: "16px 14px",
    borderRadius: "14px",
    border: "1px solid var(--table-head-border)",
    fontSize: "22px",
    fontWeight: 700,
    boxSizing: "border-box",
    background: "var(--table-bg)",
    color: "var(--text-primary)",
  },
  label: {
    display: "block",
    marginBottom: "6px",
    fontWeight: 700,
  },
  input: {
    width: "100%",
    padding: "11px 12px",
    borderRadius: "12px",
    border: "1px solid var(--table-head-border)",
    fontSize: "15px",
    boxSizing: "border-box",
    background: "var(--table-bg)",
    color: "var(--text-primary)",
  },
  buttonRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
  },
  buttonPrimary: {
    background: "linear-gradient(135deg, #0b77d8 0%, #0b5bb5 100%)",
    color: "#ffffff",
    border: "none",
    padding: "11px 18px",
    borderRadius: "12px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: 700,
    boxShadow: "0 10px 20px rgba(11, 91, 181, 0.22)",
  },
  mobileSaveButton: {
    width: "100%",
    minHeight: "56px",
    background: "linear-gradient(135deg, #0b77d8 0%, #0b5bb5 100%)",
    color: "#ffffff",
    border: "none",
    padding: "14px 20px",
    borderRadius: "14px",
    cursor: "pointer",
    fontSize: "20px",
    fontWeight: 800,
    boxShadow: "0 12px 24px rgba(11, 91, 181, 0.28)",
  },
  button: {
    background: "var(--soft-bg)",
    color: "var(--text-primary)",
    border: "1px solid var(--soft-border)",
    padding: "10px 16px",
    borderRadius: "12px",
    cursor: "pointer",
    fontSize: "15px",
  },
  buttonDanger: {
    background: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    color: "#ffffff",
    border: "none",
    padding: "11px 18px",
    borderRadius: "12px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: 700,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(155px, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  statCard: {
    background: "var(--stat-card-bg)",
    borderRadius: "16px",
    padding: "12px 13px",
    boxShadow: "var(--card-shadow)",
    border: "1px solid var(--stat-card-border)",
  },
  statCardEmphasis: {
    background:
      "linear-gradient(145deg, rgba(8, 47, 73, 0.96), rgba(11, 91, 181, 0.92))",
    color: "#e2f3ff",
    border: "1px solid rgba(125, 211, 252, 0.5)",
  },
  statCardGood: {
    border: "1px solid rgba(22, 163, 74, 0.55)",
    boxShadow: "0 10px 24px rgba(22, 163, 74, 0.15)",
  },
  statCardWarning: {
    border: "1px solid rgba(245, 158, 11, 0.6)",
    boxShadow: "0 10px 24px rgba(245, 158, 11, 0.17)",
  },
  statCardBad: {
    border: "1px solid rgba(239, 68, 68, 0.6)",
    boxShadow: "0 10px 24px rgba(239, 68, 68, 0.15)",
  },
  statTitle: {
    color: "var(--text-muted)",
    marginBottom: "6px",
    fontSize: "13px",
  },
  statTitleOnDark: {
    color: "rgba(226, 243, 255, 0.8)",
  },
  statValue: {
    fontSize: "clamp(18px, 4.5vw, 24px)",
    fontWeight: 700,
    lineHeight: 1.25,
  },
  statValueCompact: {
    fontSize: "clamp(15px, 3.4vw, 18px)",
    lineHeight: 1.35,
  },
  statValueOnDark: {
    color: "#ffffff",
  },
  statSecondaryValue: {
    marginTop: "6px",
    fontSize: "13px",
    lineHeight: 1.35,
    color: "var(--text-muted)",
    fontWeight: 600,
  },
  statSecondaryOnDark: {
    color: "rgba(226, 243, 255, 0.86)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "980px",
  },
  tableWrap: {
    overflowX: "auto",
    borderRadius: "16px",
    border: "1px solid var(--table-head-border)",
    background: "var(--table-bg)",
  },
  entryCardsList: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "8px",
  },
  mobileCollapseHeader: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "var(--soft-bg)",
    border: "1px solid var(--soft-border)",
    color: "var(--text-primary)",
    borderRadius: "12px",
    padding: "10px 12px",
    fontSize: "15px",
    fontWeight: 700,
    cursor: "pointer",
    marginBottom: "8px",
  },
  mobileCollapseChevron: {
    fontSize: "12px",
    transition: "transform 180ms ease",
  },
  entryCard: {
    background: "var(--table-bg)",
    border: "1px solid var(--soft-border)",
    borderRadius: "14px",
    padding: "12px",
  },
  entryCardCompact: {
    background: "var(--table-bg)",
    border: "1px solid var(--soft-border)",
    borderRadius: "12px",
    padding: "0",
    overflow: "hidden",
  },
  entryCardSummary: {
    listStyle: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    padding: "10px 12px",
    cursor: "pointer",
  },
  entryCardSummaryMain: {
    minWidth: 0,
    display: "grid",
    gap: "2px",
  },
  entryCardSummaryRight: {
    textAlign: "end",
    flexShrink: 0,
  },
  entryCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
    marginBottom: "10px",
  },
  entryCardTitle: {
    fontSize: "15px",
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  entryCardSubTitle: {
    fontSize: "13px",
    color: "var(--text-muted)",
  },
  entryCardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "8px",
  },
  entryCardItem: {
    background: "var(--soft-bg)",
    border: "1px solid var(--soft-border)",
    borderRadius: "10px",
    padding: "8px",
  },
  entryCardItemLabel: {
    fontSize: "12px",
    color: "var(--text-muted)",
    marginBottom: "4px",
  },
  entryCardItemValue: {
    fontSize: "14px",
    fontWeight: 700,
    color: "var(--text-primary)",
    lineHeight: 1.35,
  },
  entryCardActions: {
    marginTop: "10px",
    display: "flex",
    gap: "8px",
  },
  th: {
    textAlign: "right",
    padding: "12px 10px",
    borderBottom: "2px solid var(--table-head-border)",
    background: "var(--table-head-bg)",
    fontSize: "14px",
    color: "var(--text-muted)",
  },
  td: {
    textAlign: "right",
    padding: "13px 10px",
    borderBottom: "1px solid var(--table-row-border)",
    fontSize: "14px",
    lineHeight: 1.5,
    verticalAlign: "top",
  },
  chartGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  chartCard: {
    background: "var(--card-bg)",
    border: "1px solid var(--card-border)",
    borderRadius: "16px",
    padding: "12px",
    boxShadow: "var(--card-shadow)",
  },
  chartTitle: {
    fontSize: "14px",
    fontWeight: 700,
    marginBottom: "4px",
  },
  chartSubtitle: {
    fontSize: "12px",
    color: "var(--text-muted)",
    marginBottom: "8px",
  },
  chartSvg: {
    width: "100%",
    height: "110px",
  },
  chartAxisRow: {
    marginTop: "4px",
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
  },
  chartAxisLabel: {
    fontSize: "12px",
    color: "var(--text-muted)",
    lineHeight: 1.2,
  },
  deleteSmall: {
    background: "#dc2626",
    color: "#fff",
    border: "none",
    padding: "7px 12px",
    borderRadius: "10px",
    cursor: "pointer",
  },
  bottomBarWrap: {
    position: "fixed",
    bottom: "10px",
    left: "50%",
    transform: "translateX(-50%)",
    width: "min(760px, calc(100% - 14px))",
    zIndex: 20,
  },
  feedbackFab: {
    position: "fixed",
    bottom: "88px",
    right: "12px",
    zIndex: 26,
    background: "linear-gradient(135deg, #0ea5e9 0%, #0369a1 100%)",
    color: "#ffffff",
    border: "none",
    borderRadius: "999px",
    padding: "10px 14px",
    fontSize: "13px",
    fontWeight: 700,
    boxShadow: "0 10px 24px rgba(2, 132, 199, 0.34)",
    cursor: "pointer",
  },
  feedbackFabActive: {
    background: "linear-gradient(135deg, #0284c7 0%, #075985 100%)",
  },
  feedbackTextArea: {
    width: "100%",
    minHeight: "120px",
    padding: "12px",
    borderRadius: "12px",
    border: "1px solid var(--table-head-border)",
    background: "var(--table-bg)",
    color: "var(--text-primary)",
    fontSize: "14px",
    boxSizing: "border-box",
    resize: "vertical",
    marginBottom: "10px",
    fontFamily: "inherit",
  },
  bottomBar: {
    display: "grid",
    gridTemplateColumns: "1fr 1.2fr 1fr",
    gap: "8px",
    background: "var(--bottom-bg)",
    padding: "8px",
    borderRadius: "20px",
    border: "1px solid var(--bottom-border)",
    boxShadow: "0 12px 30px rgba(15, 23, 42, 0.16)",
    backdropFilter: "blur(10px)",
  },
  bottomNavButton: {
    background: "var(--table-bg)",
    color: "var(--text-primary)",
    border: "1px solid var(--soft-border)",
    padding: "12px 10px",
    borderRadius: "15px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 700,
  },
  bottomNavButtonActive: {
    background: "#dff1ff",
    color: "#0b63b8",
    border: "1px solid #92cbf5",
    padding: "12px 10px",
    borderRadius: "15px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 700,
  },
  bottomNavButtonPrimary: {
    background: "linear-gradient(135deg, #0e88df 0%, #0b63b8 100%)",
    color: "#ffffff",
    border: "none",
    padding: "14px 12px",
    borderRadius: "16px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: 800,
    boxShadow: "0 10px 24px rgba(11, 99, 184, 0.32)",
  },
  bottomNavButtonPrimaryActive: {
    background: "linear-gradient(135deg, #0b72c9 0%, #07508f 100%)",
    color: "#ffffff",
    border: "none",
    padding: "14px 12px",
    borderRadius: "16px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: 800,
    boxShadow: "0 14px 28px rgba(7, 80, 143, 0.32)",
  },
  moreDataGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "14px",
  },
  detailCard: {
    background: "var(--soft-bg)",
    borderRadius: "16px",
    padding: "14px",
    border: "1px solid var(--soft-border)",
  },
  fuelMapEmbed: {
    width: "100%",
    height: "280px",
    border: "1px solid var(--soft-border)",
    borderRadius: "12px",
    marginTop: "8px",
    marginBottom: "8px",
    background: "var(--table-bg)",
  },
  fuelMapLinks: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "6px",
    maxHeight: "160px",
    overflowY: "auto",
  },
  fuelMapLink: {
    fontSize: "12px",
    color: "#0b77d8",
    textDecoration: "none",
    background: "var(--soft-bg)",
    border: "1px solid var(--soft-border)",
    borderRadius: "8px",
    padding: "6px 8px",
  },
  detailLabel: {
    color: "var(--text-muted)",
    marginBottom: "8px",
    fontSize: "14px",
  },
  detailValue: {
    color: "var(--text-primary)",
    fontWeight: 700,
    lineHeight: 1.5,
  },
  monthlyCardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: "10px",
  },
  monthlyCard: {
    background: "var(--table-bg)",
    border: "1px solid var(--soft-border)",
    borderRadius: "12px",
    padding: "10px 12px",
  },
  calendarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
    flexWrap: "wrap",
  },
  calendarNav: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  calendarWeekHeaderGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    gap: "6px",
    marginBottom: "6px",
  },
  calendarWeekHeaderCell: {
    textAlign: "center",
    fontSize: "12px",
    color: "var(--text-muted)",
    fontWeight: 700,
    padding: "4px 0",
  },
  calendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    gap: "6px",
  },
  calendarDayCell: {
    minHeight: "74px",
    background: "var(--table-bg)",
    border: "1px solid var(--soft-border)",
    borderRadius: "10px",
    padding: "6px",
  },
  calendarDayCellEmpty: {
    minHeight: "74px",
    borderRadius: "10px",
    background: "transparent",
  },
  calendarDayNumber: {
    fontSize: "12px",
    fontWeight: 700,
    marginBottom: "4px",
    color: "var(--text-primary)",
  },
  calendarDayMeta: {
    fontSize: "11px",
    lineHeight: 1.35,
    color: "var(--text-muted)",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "var(--overlay-bg)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: 0,
    zIndex: 30,
  },
  modalCard: {
    width: "min(900px, 100%)",
    maxHeight: "88vh",
    overflowY: "auto",
    background: "var(--modal-bg)",
    borderRadius: "28px 28px 0 0",
    padding: "16px 18px 22px",
    boxShadow: "0 -22px 52px rgba(15, 23, 42, 0.24)",
    border: "1px solid var(--card-border)",
  },
  modalSheetHandle: {
    width: "52px",
    height: "5px",
    borderRadius: "999px",
    background: "#cbd5e1",
    margin: "4px auto 14px",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    marginBottom: "12px",
  },
  sheetContent: {
    padding: 0,
    marginBottom: 0,
    background: "transparent",
    border: "none",
    boxShadow: "none",
    borderRadius: 0,
    backdropFilter: "none",
  },
};
